export const STOPWORDS = new Set([
  'a', 'an', 'the', 'is', 'are', 'was', 'were', 'be', 'been', 'being',
  'have', 'has', 'had', 'do', 'does', 'did', 'will', 'would', 'could',
  'should', 'may', 'might', 'shall', 'can', 'need', 'dare', 'ought',
  'used', 'to', 'of', 'in', 'for', 'on', 'with', 'at', 'by', 'from',
  'as', 'into', 'through', 'during', 'before', 'after', 'above', 'below',
  'between', 'out', 'off', 'over', 'under', 'again', 'further', 'then',
  'once', 'here', 'there', 'when', 'where', 'why', 'how', 'all', 'each',
  'every', 'both', 'few', 'more', 'most', 'other', 'some', 'such', 'no',
  'nor', 'not', 'only', 'own', 'same', 'so', 'than', 'too', 'very',
  'just', 'because', 'but', 'and', 'or', 'if', 'while', 'about', 'up',
  'this', 'that', 'these', 'those', 'i', 'me', 'my', 'myself', 'we',
  'our', 'ours', 'ourselves', 'you', 'your', 'yours', 'yourself',
  'yourselves', 'he', 'him', 'his', 'himself', 'she', 'her', 'hers',
  'herself', 'it', 'its', 'itself', 'they', 'them', 'their', 'theirs',
  'themselves', 'what', 'which', 'who', 'whom', 'whose', 'am', 'get',
  'got', 'gets', 'getting', 'go', 'goes', 'going', 'gone', 'went',
  'come', 'came', 'comes', 'coming', 'make', 'makes', 'made', 'making',
  'take', 'takes', 'took', 'taken', 'taking', 'give', 'gives', 'gave',
  'given', 'giving', 'say', 'says', 'said', 'saying', 'know', 'knows',
  'knew', 'known', 'knowing', 'think', 'thinks', 'thought', 'thinking',
  'see', 'sees', 'saw', 'seen', 'seeing', 'want', 'wants', 'wanted',
  'wanting', 'use', 'uses', 'using', 'find', 'finds', 'found', 'finding',
  'also', 'back', 'still', 'well', 'way', 'even', 'new', 'now', 'old',
  'much', 'many', 'any', 'like', 'just', 'also', 'really', 'already',
  'since', 'until', 'upon', 'against', 'among', 'within', 'without',
  'along', 'around', 'behind', 'beside', 'beyond', 'down', 'near',
  'toward', 'towards', 'across', 'enough', 'another', 'anything',
  'everything', 'nothing', 'something', 'someone', 'everyone', 'anyone',
  'nobody', 'one', 'two', 'three', 'first', 'last', 'next', 'long',
  'great', 'little', 'right', 'high', 'small', 'large', 'big',
  'different', 'important', 'good', 'bad', 'best', 'worst', 'better',
  'worse', 'own', 'able', 'possible', 'likely', 'less', 'least',
  'always', 'never', 'often', 'sometimes', 'usually', 'rather',
  'quite', 'however', 'therefore', 'thus', 'hence', 'instead',
  'meanwhile', 'yet', 'already', 'perhaps', 'maybe', 'almost',
  'though', 'although', 'whether', 'either', 'neither', 'nor',
  'else', 'per', 'etc', 'via'
])
